TRUNCATE `asset`;
TRUNCATE `bulk_discount`;
TRUNCATE `collection`;
TRUNCATE `collection_asset`;
TRUNCATE `collection_channels_channel`;
TRUNCATE `collection_link`;
TRUNCATE `collection_link_translation`;
TRUNCATE `collection_product_variants_product_variant`;
TRUNCATE `collection_translation`;
TRUNCATE `facet`;
TRUNCATE `facet_translation`;
TRUNCATE `facet_value`;
TRUNCATE `facet_value_translation`;
TRUNCATE `product`;
TRUNCATE `product_asset`;
TRUNCATE `product_channels_channel`;
TRUNCATE `product_facet_values_facet_value`;
TRUNCATE `product_option`;
TRUNCATE `product_option_group`;
TRUNCATE `product_option_group_translation`;
TRUNCATE `product_option_translation`;
TRUNCATE `product_recommendation`;
TRUNCATE `product_translation`;
TRUNCATE `product_variant`;
TRUNCATE `product_variant_asset`;
TRUNCATE `product_variant_facet_values_facet_value`;
TRUNCATE `product_variant_options_product_option`;
TRUNCATE `product_variant_price`;
TRUNCATE `product_variant_translation`;
TRUNCATE `search_index_item`;
INSERT INTO `collection` (`createdAt`, `updatedAt`, `isRoot`, `position`, `isPrivate`, `filters`, `id`, `featuredAssetId`, `parentId`, `customFieldsSeodescription`, `customFieldsHaslinks`) VALUES (CURRENT_TIME(), CURRENT_TIME(), '1', '1', '0', '[]', '1', NULL, NULL, NULL, NULL);
INSERT INTO `collection_channels_channel` (`collectionId`, `channelId`) VALUES ('1', '1');
INSERT INTO `collection_translation` (`createdAt`, `updatedAt`, `languageCode`, `name`, `description`, `id`, `baseId`, `slug`) VALUES (CURRENT_TIME(), CURRENT_TIME(), 'de', 'root collection', '', NULL, '1', 'root'); 
INSERT INTO `collection_translation` (`createdAt`, `updatedAt`, `languageCode`, `name`, `description`, `id`, `baseId`, `slug`) VALUES (CURRENT_TIME(), CURRENT_TIME(), 'fr', 'root collection', '', NULL, '1', 'root');
INSERT INTO `facet` (`createdAt`, `updatedAt`, `isPrivate`, `code`, `id`) VALUES (CURRENT_TIME(), CURRENT_TIME(), '0', 'categories', '1');
INSERT INTO `facet_translation` (`createdAt`, `updatedAt`, `languageCode`, `name`, `id`, `baseId`) VALUES (CURRENT_TIME(), CURRENT_TIME(), 'de', 'Kategorie', NULL, '1');
INSERT INTO `facet_translation` (`createdAt`, `updatedAt`, `languageCode`, `name`, `id`, `baseId`) VALUES (CURRENT_TIME(), CURRENT_TIME(), 'fr', 'Catégorie', NULL, '1');
INSERT INTO `facet` (`createdAt`, `updatedAt`, `isPrivate`, `code`, `id`) VALUES (CURRENT_TIME(), CURRENT_TIME(), '0', 'reseller-discounts', '2');
INSERT INTO `facet_translation` (`createdAt`, `updatedAt`, `languageCode`, `name`, `id`, `baseId`) VALUES (CURRENT_TIME(), CURRENT_TIME(), 'de', 'Wiederverkäuferrabatt', NULL, '2');
INSERT INTO `facet_translation` (`createdAt`, `updatedAt`, `languageCode`, `name`, `id`, `baseId`) VALUES (CURRENT_TIME(), CURRENT_TIME(), 'fr', 'Reseller discounts', NULL, '2');